import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../constants/Colors';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    flex: 1,
  },
  header: {
    padding: 16,
    paddingTop: 20,
  },
  headerTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  stepTitle: {
    fontSize: 20,
    fontFamily: 'SpaceGrotesk-Bold',
    color: Colors.text,
    marginBottom: 4,
    textAlign: 'left',
  },
  progressBarContainer: {
    height: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: Colors.primary,
    borderRadius: 3,
  },
  progressCirclesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  progressCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  activeProgressCircle: {
    backgroundColor: Colors.primary,
  },
  completedProgressCircle: {
    backgroundColor: Colors.success,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  stepContent: {
    gap: 16,
  },
  card: {
    backgroundColor: Colors.cardBackground,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  budgetCard: {
    backgroundColor: 'rgba(76, 175, 80, 0.1)', // Light green background
    borderColor: 'rgba(76, 175, 80, 0.3)', // Green border
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  cardTitle: {
    fontSize: 18,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.text,
    marginLeft: 10,
  },
  budgetTitle: {
    fontSize: 18,
    fontFamily: 'SpaceGrotesk-Medium',
    color: '#4CAF50', // Green text
  },
  budgetRange: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    color: '#4CAF50', // Green text
    marginLeft: 'auto',
  },
  budgetInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  orText: {
    textAlign: 'center',
    color: Colors.textSecondary,
    marginVertical: 12,
    fontFamily: 'SpaceGrotesk-Regular',
  },
  inputLabel: {
    fontSize: 16,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.text,
    marginBottom: 8,
  },
  manualAddressInput: {
    backgroundColor: Colors.border,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    padding: 12,
    color: Colors.text,
    fontFamily: 'SpaceGrotesk-Regular',
    fontSize: 16,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  selectLimit: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    marginLeft: 8,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: Colors.background,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 10,
  },
  footerButton: {
    flex: 1,
    marginHorizontal: 5,
    height: 50,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  errorText: {
    color: Colors.error,
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    marginBottom: 8,
  },
  detectedAddressContainer: {
    marginTop: 8,
    padding: 12,
    backgroundColor: 'rgba(76, 175, 80, 0.08)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(76, 175, 80, 0.2)',
  },
  detectedAddressLabel: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.textSecondary,
    marginBottom: 4,
  },
  detectedAddressText: {
    fontSize: 15,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.text,
  },
  infoIconButton: {
    marginLeft: 8,
    padding: 4,
  },
  helperText: {
    fontSize: 13,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    marginTop: 4,
    fontStyle: 'italic',
  },
  timeVisibilityContainer: {
    marginBottom: 16,
  },
  timeDescription: {
    fontSize: 15,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    marginBottom: 12,
    lineHeight: 20,
  },
  timeEstimationSection: {
    marginBottom: 16,
  },
  timeEstimationLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    width: '100%',
  },
  timeOptionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  timeOptionButton: {
    flex: 1,
    minWidth: '45%',
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 8,
    marginBottom: 8,
  },
  deadlineContainer: {
    marginTop: 16,
  },
  deadlineText: {
    fontSize: 15,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    marginBottom: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: width * 0.85,
    backgroundColor: Colors.cardBackground,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: 'SpaceGrotesk-Bold',
    color: Colors.text,
  },
  modalCloseButton: {
    fontSize: 20,
    color: Colors.textSecondary,
    padding: 4,
  },
  modalText: {
    fontSize: 16,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.text,
    marginBottom: 12,
    lineHeight: 22,
  },
  modalSubText: {
    fontSize: 15,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    marginBottom: 8,
    fontStyle: 'italic',
  },
  modalNoteText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.primary,
    marginTop: 8,
  },
  categoryContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    marginBottom: 8,
  },
  activeCategoryButton: {
    borderColor: Colors.primary,
    backgroundColor: `${Colors.primary}20`,
  },
  categoryText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
  },
  activeCategoryText: {
    color: Colors.primary,
    fontFamily: 'SpaceGrotesk-Medium',
  },
  priorityContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  priorityButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    gap: 6,
  },
  priorityDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.textSecondary,
    marginRight: 8,
  },
  priorityText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
  },
  urgentContainer: {
    marginBottom: 16,
  },
  urgentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: 'rgba(255, 87, 51, 0.1)',
    borderRadius: 8,
    marginBottom: 12,
  },
  activeUrgentButton: {
    backgroundColor: 'rgba(255, 87, 51, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 87, 51, 0.5)',
  },
  urgentText: {
    fontSize: 16,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.textSecondary,
    marginLeft: 12,
  },
  activeUrgentText: {
    color: '#FF5733',
  },
  reviewItem: {
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  reviewLabel: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.textSecondary,
    marginBottom: 4,
  },
  reviewValue: {
    fontSize: 16,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.text,
  },
  reviewValueWithDot: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  disclaimer: {
    fontSize: 13,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    textAlign: 'center',
    marginVertical: 16,
    fontStyle: 'italic',
  },
  timeOptionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  timeOption: {
    flex: 1,
    padding: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    marginHorizontal: 4,
    borderRadius: 8,
  },
  activeTimeOption: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  timeOptionText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.text,
  },
  activeTimeOptionText: {
    color: '#FFFFFF',
    fontFamily: 'SpaceGrotesk-Bold',
  },
  customTimeContainer: {
    marginTop: 16,
  },
  contextDescription: {
    fontSize: 15,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    marginBottom: 12,
  },
  contextOptionsContainer: {
    gap: 8,
  },
  contextOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  activeContextOption: {
    backgroundColor: 'rgba(33, 150, 243, 0.1)',
    borderColor: 'rgba(33, 150, 243, 0.3)',
  },
  contextOptionText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    marginLeft: 10,
  },
  activeContextOptionText: {
    color: Colors.primary,
    fontFamily: 'SpaceGrotesk-Medium',
  },
  optionalText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    marginLeft: 8,
  },
  photoDescription: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    marginBottom: 16,
  },
  photoContainer: {
    marginTop: 12,
  },
  addressFieldsContainer: {
    marginTop: 8,
    gap: 12,
  },
  addressField: {
    marginBottom: 0,
  },
  photoPreview: {
    width: width * 0.3,
    height: width * 0.3,
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 12,
    backgroundColor: Colors.cardBackground,
    position: 'relative',
  },
  removePhotoText: {
    color: '#FFF',
    fontSize: 16,
  },
  addPhotoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
  },
  addPhotoText: {
    color: Colors.text,
    marginLeft: 8,
    fontFamily: 'SpaceGrotesk-Medium',
    fontSize: 14,
  },
  uploadPhotoButton: {
    height: 120,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  uploadPhotoText: {
    color: Colors.text,
    fontSize: 16,
    fontFamily: 'SpaceGrotesk-Medium',
    marginTop: 8,
  },
  uploadPhotoSubtext: {
    color: Colors.textSecondary,
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    marginTop: 4,
  },
  previewHeader: {
    marginBottom: 16,
  },
  previewTitle: {
    fontSize: 20,
    fontFamily: 'SpaceGrotesk-Bold',
    color: Colors.text,
    marginBottom: 4,
  },
  previewSubtitle: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
  },
  previewValue: {
    fontSize: 16,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.text,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(33, 150, 243, 0.1)',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  editButtonText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.primary,
    marginLeft: 4,
  },
  previewCategories: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  previewCategory: {
    backgroundColor: 'rgba(33, 150, 243, 0.1)',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  previewCategoryText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.primary,
  },
  previewValueWithDot: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  contextList: {
    paddingLeft: 8,
  },
  contextListItem: {
    fontSize: 15,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.text,
    marginBottom: 4,
  },
  postTaskButton: {
    backgroundColor: Colors.success,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 24,
  },
  postTaskButtonText: {
    color: '#FFF',
    fontSize: 18,
    fontFamily: 'SpaceGrotesk-Bold',
  },
  photoThumbnail: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  photoPreviewContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  removePhotoButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    width: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoPreviewSmall: {
    width: width * 0.25,
    height: width * 0.25,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: Colors.cardBackground,
  },
  skillInputContainer: {
    marginBottom: 16,
  },
  skillTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  skillTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(33, 150, 243, 0.1)',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(33, 150, 243, 0.3)',
  },
  skillTagText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.primary,
  },
  removeSkillButton: {
    marginLeft: 8,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeSkillText: {
    fontSize: 14,
    color: Colors.textSecondary,
    lineHeight: 14,
  },
  paymentOptionsContainer: {
    marginTop: 12,
    gap: 12,
  },
  paymentOption: {
    padding: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  activePaymentOption: {
    backgroundColor: 'rgba(33, 150, 243, 0.1)',
    borderColor: 'rgba(33, 150, 243, 0.3)',
  },
  paymentOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  paymentRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Colors.textSecondary,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentRadioSelected: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.primary,
  },
  paymentOptionText: {
    fontSize: 16,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.text,
  },
  paymentDescription: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    marginLeft: 32,
  },
  // Toggle section styles
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  toggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  toggleTrack: {
    width: 40,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    padding: 2,
  },
  toggleTrackActive: {
    backgroundColor: `${Colors.primary}50`,
  },
  toggleThumb: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.textSecondary,
  },
  toggleThumbActive: {
    backgroundColor: Colors.primary,
    transform: [{ translateX: 20 }],
  },
  toggleText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.textSecondary,
    marginLeft: 8,
  },
  toggleTextActive: {
    color: Colors.primary,
  },
  toggleOffText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    marginTop: 4,
    lineHeight: 20,
    fontStyle: 'italic',
  },
  // Info box styles for inline info display
  infoBox: {
    backgroundColor: `${Colors.primary}10`,
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    borderLeftWidth: 3,
    borderLeftColor: Colors.primary,
  },
  infoTitle: {
    fontSize: 16,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.primary,
    marginBottom: 6,
  },
  infoText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.text,
    lineHeight: 20,
  },
  infoSubText: {
    fontSize: 13,
    fontFamily: 'SpaceGrotesk-Regular',
    color: Colors.textSecondary,
    fontStyle: 'italic',
    marginTop: 4,
  },
  infoNoteText: {
    fontSize: 13,
    fontFamily: 'SpaceGrotesk-Medium',
    color: Colors.primary,
    marginTop: 8,
  },
  // Disabled payment option styles
  disabledPaymentOption: {
    opacity: 0.7,
    borderColor: Colors.border,
  },
  paymentRadioLocked: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.textSecondary,
  },
  comingSoonBadge: {
    backgroundColor: `${Colors.primary}20`,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginLeft: 8,
  },
  comingSoonText: {
    color: Colors.primary,
    fontSize: 10,
    fontFamily: 'SpaceGrotesk-Medium',
  },
  // Add improved review photo styles
  reviewPhotoContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 8,
  },
  reviewPhotoItem: {
    width: width * 0.28,
    height: width * 0.28,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: Colors.cardBackground,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  reviewPhotoImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
});

export default styles; 